name: Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.txt"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Pull LFS Assets from GitLab
        env:
          GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GL_REPO_URL: ${{ vars.GL_REPO_URL }}
        run: |
          echo "Setting up Git credentials for LFS..."

          git config --global credential.helper store
          echo "https://oauth2:${GL_TOKEN}@gitlab.com" > ~/.git-credentials

          git config lfs.url "${GL_REPO_URL}/info/lfs"

          git lfs pull

          echo "LFS Assets successfully downloaded into the workspace!"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
